### ISSUE TITLE
Cannot scroll in documentation

### ISSUE THREAD

**Issue by rclai** [jagi/meteor-astronomy#137]

**Comment by jagi** [comment]
Mobile or desktop?

**Comment by rclai** [comment]
Desktop.

**Comment by rclai** [comment]
Chrome.

**Comment by jagi** [comment]
Hmm it's strange. Can you describe it in more details? It's just stuck or it does not show or something else?

**Comment by rclai** [comment]
It tries to scroll but it keeps getting stuck at the top of a section.

**Comment by rclai** [comment]
I can scroll up, but it snaps to the top of the section.

**Comment by jagi** [comment]
What browser are you using?

**Comment by rclai** [comment]
Chrome 46.0.2490.71 m.

**Comment by dalcib** [comment]
The same for me.
Chrome 45.0.2454.101 m

**Comment by jagi** [comment]
What operating system?

**Comment by rclai** [comment]
Windows 7.

**Comment by dalcib** [comment]
windows 8.1

**Comment by jagi** [comment]
Ok I will take a look at it.

**Comment by roelvan** [comment]
Same issue here on a mac (chrome). Both touchpad and mouse wheel.

**Comment by roelvan** [comment]
By the way I want to thank you for this great package and the extended documentation. A real pleasure to use your package. You rock!

**Comment by jagi** [comment]
I will have to make further tests. I've experience the same problem in Chrome on Android. I'll debug it tonight.

@roelvan thanks for good words :)

**Comment by space-alien** [comment]
I wonder if the animated progress bar is somehow to blame? It seems that scroll position is affected after the progress bar animation finishes.

By the way, this problem makes the docs completely impossible to use on Chrome Android.

**Comment by jagi** [comment]
No progress bar is not the problem. The problem is in calculating current section based on the scroll position.

**Comment by jagi** [comment]
Ok I've fixed it temporarily by splitting documentation into separate pages. I will prepare entirely new documentation page soon. Let me know if you can read it now.

**Comment by space-alien** [comment]
Thanks, that works ;)  - tested on Chrome/Android.

One thing I note is that scrolling still feels very laggy on Chrome/Android. I wonder if perhaps the way the progress bar responds to scroll is a bit too keen? Perhaps a buffer to introduce a brief delay before updating the progress bar after the last scroll event might help, assuming there isn't one already.

Really enjoying my time learning about Astronomy so far - can't wait to work with it. Thanks for such a great tool.

**Comment by jagi** [comment]
@space-alien I'm using the `_.throttle` function with a time set to `200ms` so it's only doing 5 updates in a second. I've been testing documentation on Galaxy S4 and it work smooth. What phone do you have? I will probably remove progress bar in the future. It was good in a long documentation format but I'm going to keep it paginated so there will be no need for the progress bar.

Thanks, enjoy :)

**Comment by space-alien** [comment]
Sorry for the slow reply. Funnily enough, I'm also using an S4 and still seeing *really* laggy scrolling in Chrome.

In the native browser on the S4, scrolling is fine, but sadly the menu doesn't work.

Anyway, maybe this should remain a low priority since it's not affecting desktop.

**Comment by jagi** [comment]
Hmm ok I will figure something out. I will prepare a new version in near future without such things like progress indicator.

**Comment by roelvan** [comment]
I also think it’s much easier to have one long page so that you can do a quick `CMD+F/CTRL+F` to find something back.

Did you check out [Readme.io](https://readme.io/)? It’s free for open source projects and looks quite solid.

--
Roel Vaneyghen, Co-founder
www.ralphstarck.com | www.klikkid.be | www.pixelfreaks.io | www.trouweninbeeld.be | www.lost.io

On 3 November 2015 at 04:55:48, jagi (notifications@github.com) wrote:

Hmm ok I will figure something out. I will prepare a new version in near future without such things like progress indicator.

**Comment by roelvan** [comment]
@jagi I also think it’s much easier to have one long page so that you can do a quick `CMD+F/CTRL+F` to find something back.

Did you check out [Readme.io](https://readme.io/)? It’s free for open source projects and looks quite solid. You can find an example [here](https://sample-solid.readme.io/v1.0/docs).
