### ISSUE TITLE
v2.0 validate new models throws _id required error

### ISSUE THREAD

**Issue by marbemac** [jagi/meteor-astronomy#301]
```
var m = new MyModel();
m.validate();
// throws "_id" is required [validation-error]
```

_id should not be required for new models.

**Comment by jagi** [comment]
Yes I know about that problem. I will fix it

**Comment by jagi** [comment]
I'm trying to solve this problem and the problem seems to be even more complicated. The `_id` field is not the only one that is troubling. Let's say that I add the `timestamp` behavior. It adds the `createdAt` field which is required. That field similarly to the `_id` field is filled automatically during the save. As I can easily solve the problem with `_id` field then solving a problem with the `createdAt` field seems to be hard. The solution could be passing list of fields to validate.
```js
// rc.5
user.validate(['firstName', 'lastName']);
// rc.6
user.validate({ fields: ['firstName', 'lastName'] });
```
As I think about a solution there could be one but not pretties one. I could introduce `onValidate`/`beforeValidate` event that would have to be defined for behaviors like `timestamp`. In such event a behavior author would have to provide value for the `createdAt` field. However that would be also a problem because such value would be stored in the `createdAt` field. And user may not want to do it until he/she saves a document.
The other option would be introducing a new field "type/property" that would only validate such fields when saving and not when validation is run manually. What do you think?

**Comment by marbemac** [comment]
Hmm, having to define each field to validate every time is not ideal. Our models are quite complex, and nested, so this would be tough!

What about adding a dry run version of a save event (could even be internal only). It does everything a normal save would, except the resulting db insert/update. This would invoke the behaviors, etc, to populate the fields. The dry run save could create a copy before running, so that it does not effect the original model. validate() could call this save dry run method to get a resulting complete model, as it would look like just before save, and run validation on that. Would this, or something along these lines, work?

**Comment by jagi** [comment]
I've already fixed it. I solved it by making those fields optional on the client. So it works, it's already on GitHub but not published as I can published Astronomy with ES modules yet.

**Comment by marbemac** [comment]
That works! How does it work with behaviors, both official astronomy and user defined?

**Comment by jagi** [comment]
The `timestamp` behavior version on github uses the same approach, so you can use that. For custom behaviors where you have field that shouldn't be validated because value is autogenerated you should mark a field as optional. I'm doing simple trick to accomplish that.
```js
// Add a field for storing a creation date.
definition.fields['createdAt'] = {
  type: Date,
  immutable: true,
  // Make a field required only on the server.
  optional: !Meteor.isServer
};
```
So you can add `optional: !Meteor.isServer` to any field that should behave similarly.

**Comment by marbemac** [comment]
Perfect.

**Comment by Ben305** [comment]
This bug still occurs with `2.0.0-rc.8`. I try to create some demo records in `Meteor.startup`, but the call to `validate()` fails and throws that error.

**Comment by jagi** [comment]
@Ben305 without the code and reproduction it's hard to tell what's wrong

**Comment by Ben305** [comment]
@jagi Here's a sample application that reproduces the problem:
https://github.com/Ben305/Astronomy2Sample The same code was running perfectly with astronomy `1.2.x`

**Comment by Ben305** [comment]
@jagi Found the problem, pull request is here: https://github.com/jagi/meteor-astronomy/pull/340

I know auto validation is a new feature ion `2.0`, but a call to `validate` before the document was saved is not a bad practice.

**Comment by lukejagodzinski** [comment]
@Ben305 ok thanks, I've made a comment under the PR. Please take a look

**Comment by joetidee** [comment]
I am getting the following error with v2.0.0-rc.8:

```
Error: "_id" is required [validation-error]
W20160423-00:04:10.461(0)? (STDERR)     at new _class (packages/mdg:validation-error/validation-error.js:14:12)
```

This is happening when saving a new document. I am supplying the code below, but please note that I have tried both with/without the _id field being defined in the model:

models.js:

```
export const AuditTemplateModel = Class.create({
    name: 'AuditTemplateModel',
    collection: AuditTemplatesColl,
    fields: {
        _id: {
            type: String
        },
        ref: {
            type: Number,
            immutable: true
        },
        title: {
            type: String
        },
        status: {
            type: [Object],
            default: function() {
                return [];
            }
        },
        owners: {
            type: [String]
        },
        category: {
            type: [Object],
            default: function() {
                return [];
            },
            optional: true
        },
        last_audit_template_history_id: {
            type: String
        },
        created_date: {
            type: Date,
            immutable: true
        },
        created_user_id: {
            type: String,
            immutable: true
        },
        updated_date: {
            type: Date
        },
        updated_user_id: {
            type: String
        },
        discon_date: {
            type: Date
        },
        discon_user_id: {
            type: String
        }
    }
});
```

save.js:

```
let at_m = new AuditTemplateModel();
            at_m.ref = getNextSequence("AuditTemplateRef");
            at_m.status = [{
                id: 1,
                name: 'In Progress'
            }];
            at_m.title = "My Audit Template No. " + at_m.ref;
            at_m.owner_id = ['xPftXg6Ru42onGadH'];
            at_m.created_date = new Date();
            at_m.created_user_id = 'xPftXg6Ru42onGadH';
            at_m.updated_date = new Date();
            at_m.updated_user_id = 'xPftXg6Ru42onGadH';
            if (at_m.validate()) {
                at_m.save(function(err, id) {
                    console.log("Audit Template failed to save.");
                });
            }
```

**Comment by lukejagodzinski** [comment]
@joetidee the rc8 version has this bug but the actual version that is on GitHub has this bug fixed. So if you really need this right now you can clone repository to your local packages directory. I'm not going to release next rc version before release of 2.0. And release show be soon. I'm finishing documentation so after that I'm releasing 2.0

**Comment by joetidee** [comment]
I haven't ever done a cloning to packages directory before - how do I do this?

**Comment by joetidee** [comment]
Sorry, how do I do this?

**Comment by lukejagodzinski** [comment]
@joetidee you just have to `git clone https://github.com/jagi/meteor-astronomy.git` into your `project/packages` directory.

**Comment by lukejagodzinski** [comment]
Fixed. Closing this issue because I'm preparing to release 2.0
