### ISSUE TITLE
[v2] Object type percolates down if structure is undefined

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#376]
Let a field definition be

```
filters: Object
```

If I save the document with `filters = {values: [1, 2]}` filters.values is also saved as an object and not array.

**Comment by lukejagodzinski** [comment]
I will check it out

**Comment by s7dhansh** [comment]
This happens for any Javascript Object, not just arrays.

**Comment by lukejagodzinski** [comment]
I've tested it and it's working properly, so you're probably doing something wrong.

**Comment by s7dhansh** [comment]
Kindly check the 'object' branch of https://github.com/s7dhansh/astronomy-problem. It is a reprod of the problem. Check the JS console where the field is printed before and after save. Before save, it is a Date object, but post save it is just an Object.

**Comment by s7dhansh** [comment]
@jagi did you get time to check this?

**Comment by lukejagodzinski** [comment]
Sorry I'm on business trip right now and didn't have time to take a look at it yet. But I will probably investigate it today.

**Comment by lukejagodzinski** [comment]
@s7dhansh I've probably fixed it when working on a different issue. I think they were correlated. So please check out the current version of the Astronomy from the GitHub repository. Just clone it to your packages directory. I think it should work now.

**Comment by s7dhansh** [comment]
@jagi checked the latest v2 from github. Not fixed yet.

If you want you can check out the "object" branch of this repo: https://github.com/s7dhansh/astronomy-problem and click on the button. There are 2 ouputs in the console, one before and one after the save.

![issue](https://cloud.githubusercontent.com/assets/706996/15281146/330c3712-1b56-11e6-9a18-66ea2667a741.png)

**Comment by lukejagodzinski** [comment]
You are definitely not using the newest version from GitHub
<img width="1280" alt="screen shot 2016-05-16 at 19 42 30" src="https://cloud.githubusercontent.com/assets/1051229/15287520/6559f27a-1b9e-11e6-9c1a-8081bcdcebfe.png">

**Comment by s7dhansh** [comment]
The latest v2 branch, right? or any other branch?

**Comment by s7dhansh** [comment]
Ah. So I was using the latest version, but my db had the old document which already had "{}" in the `on` field. Cleared the db. It is working now. Thanks.

**Comment by lukejagodzinski** [comment]
Ok good to hear
