### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Lukasvo** [jagi/meteor-astronomy#580]
Hi all,

First of all, jagi, I would like to congratulate you with this fantastic package! I've been replacing a couple of packages I used before with Astronomy and my code is a lot cleaner ever since.

I've come across a TypeError of which I can't seem to find the cause though.
Does anyone have an idea where I should be looking?

```
TypeError: Cannot read property 'prototype' of undefined
    at packages/jagi:astronomy/lib/modules/fields/type.js:55:39
    at predicate (/Users/lvo/.meteor/packages/jagi_astronomy/.2.3.11.kl0bjy++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:5122:46)
    at baseFindIndex (/Users/lvo/.meteor/packages/jagi_astronomy/.2.3.11.kl0bjy++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:823:11)
    at findIndex (/Users/lvo/.meteor/packages/jagi_astronomy/.2.3.11.kl0bjy++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:7260:14)
    at Function.length [as find] (/Users/lvo/.meteor/packages/jagi_astronomy/.2.3.11.kl0bjy++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:5124:21)
    at Function.find (packages/jagi:astronomy/lib/modules/fields/type.js:54:14)
    at packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:29:23
    at isBind (/Users/lvo/.meteor/packages/jagi_astronomy/.2.3.11.kl0bjy++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4970:15)
    at baseForOwn (/Users/lvo/.meteor/packages/jagi_astronomy/.2.3.11.kl0bjy++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:3020:24)
    at index (/Users/lvo/.meteor/packages/jagi_astronomy/.2.3.11.kl0bjy++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4939:18)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by lukejagodzinski** [comment]
Hi, thanks.

Without code it's hard to tell what's wrong. Post some code that is causing this error. But you're probably using a type that does not exist or you haven't imported.

**Comment by Lukasvo** [comment]
Thanks for your response, jagi!

You were right: it was an import issue. I wasn't aware that you don't have to use curly braces when importing a default export..

So 
`import {Participant} from "./participants.js";`
didn't work, but the following did:
`import Participant from "./participants";`

Sorry for bothering you with this, I'm only just getting to know Javascript better :-)

**Comment by gantu** [comment]
I am facing exactly same issue, here is the code: 
```
`
import {surveys} from '/lib/collections';
import  { Class }  from 'meteor/jagi:astronomy';

const Survey = Class.create({
    name:'Survey',
    collection:surveys,
    fields:{
        name: {
            type: String
        },
        description:{
            type: String
        },
        author:{
            type: String
        },
        questions:{
            type: [Question],
            default: function(){
                return [];
            }
        }
    }
    
});
    
export const Question = Class.create({
    name:'Question',
    fields:{
        name:{
            type: String
        },
        required:{
            type: Boolean
        },
        q_type: {
            type: String
        },
        options:{
            type: [Option],
            default: function(){
                return [];
            }
        }   
    }
});

export const Option = Class.create({
    name:'Option',
    fields:{
        name: {
            type: String
        }
    }
});

export default Survey; 
```
`
Entry in /lib/collection.js : 

`export const surveys = new Mongo.Collection('surveys');`

What can be the cause of the error: 

`W20170313-15:22:07.121(6)? (STDERR) TypeError: Cannot read property 'prototype' of undefined
W20170313-15:22:07.121(6)? (STDERR)     at packages/jagi:astronomy/lib/modules/fields/type.js:55:39
W20170313-15:22:07.121(6)? (STDERR)     at predicate (/home/wild/.meteor/packages/jagi_astronomy/.2.3.12.13a2766++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:5122:46)
W20170313-15:22:07.123(6)? (STDERR)     at baseFindIndex (/home/wild/.meteor/packages/jagi_astronomy/.2.3.12.13a2766++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:823:11)
W20170313-15:22:07.124(6)? (STDERR)     at findIndex (/home/wild/.meteor/packages/jagi_astronomy/.2.3.12.13a2766++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:7260:14)
W20170313-15:22:07.125(6)? (STDERR)     at Function.find (/home/wild/.meteor/packages/jagi_astronomy/.2.3.12.13a2766++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:5124:21)
W20170313-15:22:07.125(6)? (STDERR)     at Function.find (packages/jagi:astronomy/lib/modules/fields/type.js:54:14)
W20170313-15:22:07.125(6)? (STDERR)     at packages/jagi:astronomy/lib/modules/fields/hooks/apply_definition.js:29:23
W20170313-15:22:07.126(6)? (STDERR)     at /home/wild/.meteor/packages/jagi_astronomy/.2.3.12.13a2766++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4970:15
W20170313-15:22:07.126(6)? (STDERR)     at baseForOwn (/home/wild/.meteor/packages/jagi_astronomy/.2.3.12.13a2766++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:3020:24)
W20170313-15:22:07.126(6)? (STDERR)     at /home/wild/.meteor/packages/jagi_astronomy/.2.3.12.13a2766++os+web.browser+web.cordova/npm/node_modules/lodash/lodash.js:4939:18
`

**Comment by gantu** [comment]
Issue is resolved, by defining classes in correct order.

**Comment by RileyDavidson-Evans** [comment]
@gantu I'm experiencing the same issue, how exactly did you resolve this ?

**Comment by kahmali** [comment]
Just a note: This can also happen if you pass a malformed object as the options in an Astronomy class' `fields` definition. This happened to me while defining a custom Behavior. A field definition was missing the `type` property. Just wanted to mention it in case anyone else comes across the error and you're confident that you've imported everything correctly (in which case none of the solutions above will fix it). 

Did you ever end up resolving it @RileyDavidson-Evans?

**Comment by lukejagodzinski** [comment]
For anyone having this issue:
1. Make sure that your class is correctly constructed. The easiest way of doing it is by `consol.log` it and checking if it's a function (class). If not then you probably made some error when proving class definition.
2. If class is properly created and you still have this problem then make sure that order in which you defined classes is correct. When you're defining subclass, it's good to always put its definition before using it in another class. When you use the `var` keyword to declare classes then in theory it will [hoist](https://www.w3schools.com/js/js_hoisting.asp) all the declaration to the top but you shouldn't relay on it. The best way is just to use the `const` keyword and put the `Option` class declaration before `Question` and declaration of `Question` before `Survey`.

**Comment by burakonero** [comment]
Hello I am trying to run a game that I made a few years ago and get this error. The game was working a few years ago nothing changed except nodejs version.. What causes this?

**Comment by lukejagodzinski** [comment]
@burakonero I'm not a wizard and it's really impossible to tell what caused a problem without a single line of code and at least error message that you get...

**Comment by burakonero** [comment]
@lukejagodzinski I am not a wizard either. I googled it. Problem solved when I changed var EventEmitter = process.EventEmitter to var EventEmitter = require('events') in some of js files that are located at node_modules/socked.io/lib. The reason of the error is my game is created 3 years ago this code is not suitable with new node.js system.

**Comment by lukejagodzinski** [comment]
@burakonero so problem is not even related with astronomy

**Comment by diavrank** [comment]
Hi, I am getting the same error. My class types are the following:

```ts

import { Meteor } from 'meteor/meteor';
import { Class } from 'meteor/jagi:astronomy';
import { Profile } from '/imports/api/Profiles/Profile';

const UserProfile = Class.create({
	name: 'UserProfile',
	fields: {
		profile: String,
		name: String,
		path: String
	}
});

const UserStatus = Class.create({
	name: 'UserStatus',
	fields: {
		online: Boolean,
		idle: Boolean,
		lastLogin: {
			date: Date,
			ipAddress: String,
			userAgent: String
		}
	}
});

export const User = Class.create({
	name: 'User',
	collection: Meteor.users,
	fields: {
		_id: String,
		createdAt: Date,
		emails: {
			type: [Object],
			default: function() {
				return [];
			}
		},
		username: String,
		profile: {
			type: UserProfile,
			default: function() {
				return {};
			}
		},
		status: {
			type: UserStatus,
			default: function() {
				return { online: false };
			}
		}
	},
	helpers: {
		getProfile() {
			// @ts-ignore
			return Profile.findOne({ name: this.profile.profile });
		}
	}
});
```

I was wondering if it is correct the pattern for type definition for UserStatus class?

**Comment by lukejagodzinski** [comment]
@diavrank you have to create type for `UserStatus.lastLogin`. You can't nest definitions like that.

**Comment by diavrank** [comment]
Thank you @lukejagodzinski .

I share my correct code:

```ts
import { Meteor } from 'meteor/meteor';
import { Class } from 'meteor/jagi:astronomy';
import { Profile, ProfileType } from '/imports/api/Profiles/Profile';

interface UserStatusType {
	online: boolean;
	idle?: boolean;
	lastLogin?: any;
}

const UserStatus = Class.create<UserStatusType>({
	name: 'UserStatus',
	fields: {
		online: Boolean,
		idle: {
			type: Boolean,
			optional: true
		},
		lastLogin: {
			type: Object,
			optional: true
		}
	}
});

interface UserProfileType {
	profile: string;
	name: string;
	path?: string;
}

const UserProfile = Class.create<UserProfileType>({
	name: 'UserProfile',
	fields: {
		profile: String,
		name: String,
		path: { type: String, optional: true }
	}
});

export interface UserType extends Meteor.User {
	profile: UserProfileType;
	status: UserStatusType;

	getProfile(): ProfileType;
}

export const User = Class.create<UserType>({
	name: 'User',
	collection: Meteor.users as unknown as Mongo.Collection<UserType>,
	fields: {
		createdAt: Date,
		emails: {
			type: [Object],
			default: function() {
				return [];
			}
		},
		username: String,
		profile: {
			type: UserProfile,
			default: function() {
				return {};
			}
		},
		status: {
			type: UserStatus,
			default: function() {
				return { online: false };
			}
		}
	},
	helpers: {
		getProfile() {
			return Profile.findOne({ name: this.profile.profile });
		}
	}
});

```
